mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^taskmanager/', include('taskmanager.urls', namespace='taskmanager')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace='account')),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = (
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
)


'''
#values superseded by generic view(s)
# ex: /polls/
url(r'^$', views.index, name='index'),
# ex: /polls/5/
url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
# ex: /polls/5/results/
url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
# ex: /polls/5/vote/
url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
###
'''

taskmanager/urls.py
from django.conf.urls import url

from . import views

urlpatterns = (
    #/taskmanager/
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/taskmanager/new/
    url(r'^new/$', views.CreateView.as_view(), name='new'),
    #/taskmanager/1/
    url(r'^(?P<pk>[0-9]+)/$', views.edit_task, name='edit'),
    #/taskmanager/1/delete/
    url(r'^(?P<task_id>[0-9]+)/delete/$', views.delete, name='delete'),
    #/taskmanager/1/editinplace/
    url(r'^(?P<pk>[0-9]+)/editinplace/$', views.editinplace, name='editinplace'),
)

taskmanager/models.py
from django.db import models

from datetime import datetime
from django.utils import timezone

from django.core.urlresolvers import reverse

# Create your models here.

class Task(models.Model):
    short_description = models.CharField(max_length=200)
    long_description = models.TextField()
    deadline = models.DateField()
    assigned_user = models.ForeignKey('account.MyUser', default=None, null=True)
    date_added = models.DateTimeField('date added', auto_now_add=True, null=True)
    last_modified = models.DateTimeField('last modified', auto_now=True, null=True)

    def __unicode__(self):
        return self.short_description

    def get_absolute_url(self):
        return reverse('taskmanager:edit', kwargs={"pk":self.id})

    class Meta:
        permissions = (
                ("create_task", "Can create new tasks"),
                ("edit_task", "Can modify tasks"),
                ("remove    _task", "Can delete tasks"),
        )

taskmanager/forms.py
from django import forms

from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ()#'date_added','last_modified',)

        widgets = {
            'deadline': forms.TextInput(attrs={'class': 'datepicker'}),
        }

taskmanager/views.py
from django.shortcuts import get_object_or_404, render, render_to_response

from django.views import generic

from .models import Task
from .forms import TaskForm

from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest, request
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator

from django.http import request
from django.core import exceptions

# this is the official way to do it from the docs, but still :)
# class LoginRequiredMixin(object):
#    @classmethod
#    def as_view(cls, **initkwargs):
#        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
#        return login_required(view)


class LoginRequiredMixin(object):
    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


class AdminRequiredMixin(object):
    @method_decorator(user_passes_test(lambda u: u.is_admin))
    def dispatch(self, *args, **kwargs):
        return super(AdminRequiredMixin, self).dispatch(*args, **kwargs)


class IndexView(LoginRequiredMixin,generic.ListView):
    def get_queryset(self):
        if self.request.user.is_admin:
            return Task.objects.all()
        else:
            try:
                return Task.objects.get(assigned_user=self.request.user)
            except exceptions.ObjectDoesNotExist:
                return None
    context_object_name = 'task_list'
    template_name = 'taskmanager/index.html'


@user_passes_test(lambda u: u.is_admin)
def edit_task(request, pk):
    task = get_object_or_404(Task, id=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task.save()
            return HttpResponseRedirect(reverse('taskmanager:index'))
    else:
        form = TaskForm(instance=task)
    return render(request, 'taskmanager/edit.html', {'form': form})


class CreateView(AdminRequiredMixin,generic.CreateView):
    model = Task
    template_name = 'taskmanager/create.html'
    form_class = TaskForm


@user_passes_test(lambda u: u.is_admin)
def delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.delete()
    return HttpResponseRedirect(reverse('taskmanager:index'))


@user_passes_test(lambda u: u.is_admin)
def editinplace(request, pk):
    task = get_object_or_404(Task, id=pk)
    field_name = request.POST.get("name", None)
    field_value = request.POST.get("value")
    data = {field_name: field_value}
    form = TaskForm(data, instance=task)
    if field_name not in form.errors:
        setattr(task, field_name, field_value)
        task.save()
        return HttpResponse()

taskmanager/templates/taskmanager/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='{% static "taskmanager/css/jquery-ui.css" %}'>
    <link rel="stylesheet" href='{% static "taskmanager/css/taskmanager.css" %}'>

    <script src="{% static "taskmanager/js/jquery.min.js" %}"></script>
    <script src="{% static "taskmanager/js/jquery-ui.min.js" %}"></script>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jqueryui-editable/css/jqueryui-editable.css" rel="stylesheet"/>
    <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jqueryui-editable/js/jqueryui-editable.min.js"></script>

    {% block head %}
    {% endblock %}

    <title>{% block title %}{% endblock %}</title>

</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 text-center col-lg-offset-3" style="padding-top:5%;">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>

    {% block js %}
    {% endblock %}
</body>
</html>

taskmanager/templates/taskmanager/create.html
{% extends "taskmanager/base.html" %}
{% load staticfiles %}

{% block title %}Create new Task{% endblock %}
{% block content %}
    <form action='' method="post">
        {% csrf_token %}
             {{ form.as_p }}
        <input type="submit" value="Create" />
    </form>
{% endblock %}

{% block js %}
    <script src="{% static "taskmanager/js/taskmanager.js" %}"></script>
{% endblock %}

taskmanager/templates/taskmanager/edit.html
{% extends "taskmanager/base.html" %}
{% load staticfiles %}

{% block title %}Edit Task {{ object.id }}{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
    <form action='' method="post">
        {% csrf_token %}
             {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
{% endblock %}

taskmanager/templates/taskmanager/index.html
{% extends "taskmanager/base.html" %}
{% load staticfiles %}

{% block title %}Task index{% endblock %}

{% block content %}
    <table class="table">
        {% if task_list %}
        <thead>
            <td colspan="2">
                Short Description
            </td>
            <td>
                Long Description
            </td>
            <td>
                Deadline
            </td>
            <td>
                Created date
            </td>
            <td>

            </td>
            <td>

            </td>
        </thead>
        {% for task in task_list %}
            <tr>
                <td colspan="2">
                    <a href="#" class="task-short-description" data-name="short_description" data-pk="{{ task.id }}" data-url="{% url 'taskmanager:editinplace' task.id %}">
                        {{ task.short_description }}
                    </a>
                </td>
                <td>
                    <a href="#" class="task-long-description" data-name="long_description" data-pk="{{ task.id }}" data-url="{% url 'taskmanager:editinplace' task.id %}">
                        {{ task.long_description }}
                    </a>
                </td>
                <td>
                    <a href="#" class="task-deadline" data-name="deadline" data-pk="{{ task.id }}" data-url="{% url 'taskmanager:editinplace' task.id %}">
                        {{ task.deadline }}
                    </a>
                </td>
                <td>
                    {{ task.date_added}}
                </td>
                <td>
                    <a href='{% url "taskmanager:edit" task.pk %}'><button type="button" class="btn btn-warning">Edit Task</button></a>
                </td>
                <td>
                    <a href='{% url "taskmanager:delete" task.pk %}'><button type="button" class="btn btn-danger">Delete Task</button></a>
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="7">
                <a href="{% url 'taskmanager:new' %}"><button type="button" class="btn btn-success">Create new Task</button></a>
            </td>
        </tr>
        {% else %}
            <p>What is tasks?</p>
        {% endif %}
    </table>
{% endblock %}

{% block js %}

<script>
$.fn.editable.defaults.mode = 'inline';
$.fn.editable.defaults.params = {csrfmiddlewaretoken: '{{ csrf_token }}',}

$(document).ready(function(){
    $('.task-short-description').editable({
        type: 'text',
        title: 'Task short description',
    });
    $('.task-long-description').editable({
        type: 'textarea',
        title: 'Task long description',
    });
    $('.task-deadline').editable({
        type: 'date',
        title: 'Task deadline',
    });
});
</script>
{% endblock %}